services:
  turbo_py:
    build: .
    container_name: s366_turbo
    ports:
      - "5005:5000"
    volumes:
      - .:/app
      - ./data/companies_data:/companies_data
      - ./data/users_data:/users_data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      s366:
        ipv4_address: 172.27.0.50
    #command: python3 run.py
    #command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000 --timeout 120
    #command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --workers 2 --limit-concurrency 12 --timeout-keep-alive 120

networks:
  s366:
    external: true
