services:
  turbo_py:
    build: .
    container_name: s366_turbo
    # Folosim portul 5005 pe gazdă pentru a lăsa 5000 liber pentru aplicația veche
    # Dar în interiorul containerului aplicația rulează tot pe 5000
    ports:
      - "5005:5000"
    volumes:
      - .:/app
      - ./companies_data:/companies_data
      - ./users_data:/users_data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  
              capabilities: [gpu, utility] 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all  
      - OLLAMA_NUMA=true
      - OLLAMA_KEEP_ALIVE=-1
    networks:
      s366:
        ipv4_address: 172.27.0.50 # Un IP diferit față de cel de test
    # Comanda de start pentru FastAPI (Uvicorn)
    # --reload înseamnă că se restartează la orice modificare de cod
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload

networks:
  s366:
    external: true
